### PR TITLE
feat: set up linting

### LINKED ISSUE #2: Set up linting
### Motivation

It would be great to have a common code format specification.

### Proposed solution

* Use ESLint recommended set up and adjust the code by that.
* implement npm script called lint to run lint (without the fix option) to be able to joint this check for pre-commit/CI pipeline

### Additional context

*  [.eslintrc.json](https://eslint.org/docs/user-guide/configuring

### PR DESCRIPTION
**Pull request by alenakhineika**
### Motivation

Includes:
- adding `eslint` to the project
- using `eslint-config-standard` style guide
- creating `precommit` hook
- code refactoring to match `eslint` rules

Closes #2 

### Checklist

- [x] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [x] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### CODE REVIEW

**Comment by Simply007** [comment]
Hello @alenakhineika,

thanks for the pull request. I went through the changes and all of them looks legit.

Could you please include the package-lock.json to fix the automatic check?

**Comment by alenakhineika** [comment]
@Simply007 done!

**Comment by Simply007** [comment]
@alenakhineika, 
May I ask you how did you find this issue?

**Comment by alenakhineika** [comment]
@Simply007 I found it hare: https://up-for-grabs.net/
Wanted to see how contributing process is happening in general: how people pick a task, decide who will implement a task if there are many volunteers, participate in a discussion, how quick project owners reply, etc.
I understand that it is not the same situation for every project, but anyway. I picked a well-known task for me to make it quick and that is it. So your project is my first non-profit code contribution :)

**Pull request merged**
